#!/bin/bash

if [ $# -lt 2 ];
then
	echo "Usage: $0 <user to monitor> <delay time>"
	echo ""
	exit 1
fi

while true
do
	CMD="w | grep -P \"^$1( |\$)\" | awk '{print \$5}'"
	echo "By $(date)"
	eval "$CMD"
	echo ""
	sleep "$2"
done
