#!/usr/bin/expect --
set timeout -1

# Check remote machine sshd status
#
# Usage:
# expect remote_stat.exp <username> <target> <ssh port> <password>

if { [llength $argv] < 4 } {
	puts "usage: "
	puts "expect remote_stat.exp \\"
	puts "			<username> <target> <ssh port> <password>"
	exit 1
}

set username [lindex $argv 0]
set target [lindex $argv 1]
set ssh_port [lindex $argv 2]
set password [lindex $argv 3]

source "remote.tcl"

remote_sudocmd $username $target $ssh_port $password \
		"exit"
